version: '3'
services:
  db:
      image: postgres
      container_name: posiapp-postgres
      volumes:
        - ./tmp/db:/var/lib/postgresql/data
      command: "postgres -c 'max_connections=500'"
      environment:
        POSTGRES_DB: positrace
        POSTGRES_USER: posiapp
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
  posiapp-web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: positrace
      DB_USERNAME: positrace
      DB_PASSWORD: password
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
networks:
  default:
    name: posiApp_default
